//! SeaORM Entity. Generated by sea-orm-codegen 0.2.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "cards")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub level: String,
    pub level_setting_in_use: Uuid,
    #[sea_orm(column_type = "Custom(\"jsonb\".to_owned())")]
    pub extra_data: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::level_settings::Entity",
        from = "Column::LevelSettingInUse",
        to = "super::level_settings::Column::Id",
        on_update = "SetNull",
        on_delete = "Cascade"
    )]
    LevelSettings,
}

impl Related<super::level_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LevelSettings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
